# Generated by Django 5.2.5 on 2025-08-27 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ تشکیل"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="حذف شده"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=60, unique=True, verbose_name="نامک"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        unique=True,
                        verbose_name="متا:عنوان",
                    ),
                ),
                (
                    "excerpt",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="متا:توضیحات"
                    ),
                ),
                ("priority", models.PositiveIntegerField()),
                ("header", models.CharField(max_length=100, verbose_name="عنوان")),
                (
                    "body",
                    models.TextField(
                        blank=True, max_length=10000, verbose_name="بدنه\u200cی محتوا"
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        upload_to="images/heading_image/", verbose_name="تصویر اصلی"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("F", "پیش نویس"),
                            ("S", "ثبت شده"),
                            ("A", "تایید شده"),
                            ("P", "منتشر شده"),
                            ("C", "آرشیو"),
                        ],
                        default="F",
                        max_length=2,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="article_authors",
                        related_query_name="article_author",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نویسنده",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BookmarkModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ تشکیل"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="حذف شده"),
                ),
                (
                    "is_bookmarked",
                    models.BooleanField(default=True, verbose_name="نشان شده"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        related_query_name="bookmark",
                        to="articles.articlemodel",
                        verbose_name="مقاله",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        related_query_name="bookmark",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CommentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ تشکیل"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="حذف شده"),
                ),
                ("text", models.CharField(blank=True, max_length=250)),
                (
                    "aritcle",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="articles.articlemodel",
                        verbose_name="مقاله",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContributorModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ تشکیل"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="حذف شده"),
                ),
                (
                    "date_contrib",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ مشارکت"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="تایید شده"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articles.articlemodel",
                        verbose_name="مقاله",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
