# Generated by Django 5.2.5 on 2025-08-27 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ تشکیل"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="حذف شده"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=60, unique=True, verbose_name="نامک"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        unique=True,
                        verbose_name="متا:عنوان",
                    ),
                ),
                (
                    "excerpt",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="متا:توضیحات"
                    ),
                ),
                ("priority", models.PositiveIntegerField()),
                ("header", models.CharField(max_length=100, verbose_name="عنوان")),
                (
                    "text",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="متن خبر"
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        upload_to="images/heading_image/", verbose_name="تصویر اصلی"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("F", "پیش نویس"),
                            ("S", "ثبت شده"),
                            ("A", "تایید شده"),
                            ("P", "منتشر شده"),
                            ("C", "آرشیو"),
                        ],
                        default="F",
                        max_length=2,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news_authors",
                        related_query_name="news_author",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نویسنده",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        db_table="tag",
                        related_name="news_tags",
                        related_query_name="news_tag",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LikeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ تشکیل"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="حذف شده"),
                ),
                ("liked", models.BooleanField(verbose_name="پسند")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news.newsmodel",
                        verbose_name="خبر",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
