# Generated by Django 5.2.5 on 2025-08-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ تشکیل"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="حذف شده"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=60, unique=True, verbose_name="نامک"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        unique=True,
                        verbose_name="متا:عنوان",
                    ),
                ),
                (
                    "excerpt",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="متا:توضیحات"
                    ),
                ),
                ("priority", models.PositiveIntegerField()),
                (
                    "name",
                    models.CharField(max_length=10, unique=True, verbose_name="نشانک"),
                ),
                ("hyped", models.BooleanField(default=False, verbose_name="بخار شده")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="newsmodel",
            name="tags",
            field=models.ManyToManyField(
                db_table="tag_news",
                related_name="news_tags",
                related_query_name="news_tag",
                to="news.tagmodel",
            ),
        ),
    ]
