# Generated by Django 5.2.5 on 2025-08-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_tagmodel_alter_newsmodel_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsmodel",
            name="tags",
            field=models.ManyToManyField(
                db_table="tag_news",
                related_name="news_tags",
                related_query_name="news_tag",
                to="news.tagmodel",
                verbose_name="تگ\u200cها",
            ),
        ),
    ]
