# Generated by Django 5.2.5 on 2025-08-26 08:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usermodel",
            options={},
        ),
        migrations.AddField(
            model_name="adminmodel",
            name="bio",
            field=models.CharField(blank=True, max_length=1200, verbose_name="شرح حال"),
        ),
        migrations.AddField(
            model_name="adminmodel",
            name="content_published_num",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="تعداد محتوای نشری"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="adminmodel",
            name="content_submitted_num",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="تعداد محتوای ثبتی"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="adminmodel",
            name="sectors",
            field=models.CharField(
                default="__none__", max_length=100, verbose_name="حوزه"
            ),
        ),
        migrations.AddField(
            model_name="adminmodel",
            name="user",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="admins",
                related_query_name="person",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مشخصات کاربر",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="authormodel",
            name="bio",
            field=models.CharField(blank=True, max_length=700, verbose_name="شرح حال"),
        ),
        migrations.AddField(
            model_name="authormodel",
            name="content_submitted_num",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="تعداد محتوای ثبتی"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="authormodel",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="تایید شده"),
        ),
        migrations.AddField(
            model_name="supervisormodel",
            name="bio",
            field=models.CharField(blank=True, max_length=700, verbose_name="شرح حال"),
        ),
        migrations.AddField(
            model_name="supervisormodel",
            name="content_published_num",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="تعداد محتوای نشری"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supervisormodel",
            name="sectors",
            field=models.CharField(
                default="__none__", max_length=100, verbose_name="حوزه"
            ),
        ),
        migrations.AddField(
            model_name="supervisormodel",
            name="user",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supervisors",
                related_query_name="person",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مشخصات کاربر",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usermodel",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="حذف شده"),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="name",
            field=models.CharField(blank=True, max_length=50, verbose_name="نام"),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "کاربر"), (1, "نویسنده"), (2, "سرپرست"), (3, "مدیر")],
                default=0,
                verbose_name="رول",
            ),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="telephone",
            field=models.CharField(
                blank=True,
                max_length=13,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="phone must be in this format: `(+98|0)9123456789`",
                        regex="^(\\+\\d{2}|0)9\\d{9}$",
                    )
                ],
                verbose_name="شماره همراه",
            ),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="authormodel",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="authors",
                related_query_name="person",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مشخصات کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="username",
            field=models.CharField(
                max_length=25, unique=True, verbose_name="نام کاربری"
            ),
        ),
    ]
