# Generated by Django 5.2.5 on 2025-08-27 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_usermodel_options_adminmodel_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminmodel",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="admin",
                related_query_name="person",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مشخصات کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="authormodel",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="author",
                related_query_name="person",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مشخصات کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="supervisormodel",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supervisor",
                related_query_name="person",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مشخصات کاربر",
            ),
        ),
    ]
