# Generated by Django 5.2.5 on 2025-08-27 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ تشکیل"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="حذف شده"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=60, unique=True, verbose_name="نامک"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        unique=True,
                        verbose_name="متا:عنوان",
                    ),
                ),
                (
                    "excerpt",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="متا:توضیحات"
                    ),
                ),
                ("priority", models.PositiveIntegerField()),
                ("header", models.CharField(max_length=100, verbose_name="عنوان")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=8000, verbose_name="توضیحات"
                    ),
                ),
                (
                    "followings",
                    models.ManyToManyField(
                        db_table="followings",
                        related_name="category_followings",
                        related_query_name="following",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
